# Ansible Workshop on IBM i
# Copyright © FormaServe Systems Ltd 2022
# April 2022
#
---
 - name: Show Error Handling
   hosts: localhost
   gather_facts: false

   tasks:
     - block:
        - name: List home directory
          command: "ls -l ~/"

        - name: Fail
          command: "ls -l /tmp/does-not-exist"

       rescue:
        - name: Rescue block that performs recovery
          debug:
            msg: "Ops, something went wrong ..."

       always:
        - name: Run everytime
          debug:
            msg: "I will execute even in failure scenario"