# Ansible Workshop on IBM i
# Copyright © FormaServe Systems Ltd 2022
# April 2022
#
---
- name: Create Ansible environment
  hosts: ibmi
  gather_facts: false
  collections:
    - ibm.power_ibmi
  vars:
    users:
    - AJESSICAJ
    - AEMILYY
    - ASAMMYJ
    - ACHLOEY
    - AELLIEJ

  tasks:

  - name: Create home directory for user
    file:
      path: /home/{{ item }}
      state: directory
      mode: 0744
    loop: "{{ users }}"

  - name: Creating an empty file
    file:
      path: "/home/{{ item }}/test.txt"
      state: touch
    loop: "{{ users }}"
