# Ansible Workshop on IBM i
# Copyright © FormaServe Systems Ltd 2022
# April 2022
#
---
- name: Uses shell module to retrieve domain info
  hosts: ibmi
  gather_facts: true

  tasks:

  - name: What is our domain?
    debug:
      msg: "Domain name: {{ ansible_facts['domain'] }}"

