# Ansible Workshop on IBM i
# Copyright © FormaServe Systems Ltd 2022
# April 2022
#
---
- name: Install basic packages
  hosts: ibmi

  tasks:
  - name: install open-source
    yum:
      name: andy
      state: present
    ignore_errors: true

  - name: install next
    yum:
      name: jane
      state: present
