# Ansible Workshop on IBM i
# Copyright © FormaServe Systems Ltd 2022
# April 2022
#
---
- name: Create Ansible environment for iUG Workshop
  hosts: ibmi
  gather_facts: false
  collections:
    - ibm.power_ibmi
  vars:
    users:
    - AAndy
    - AJane
    - JRiddle

  tasks:
  - name: Create User Profile
    ibmi_user_and_group:
      operation: create
      user: "{{ item }}"
      password: 'abc123'
      user_class: '*SECOFR'
      status: '*ENABLED'
      owner: '*USRPRF'
      parameters: 'HOMEDIR("/home/{{ item }}") CURLIB({{ item }})'
      text: 'Created using Ansible Playbook by FormaServe'
      become_user: QSECOFR
      become_user_password: 'NoIdea'
    loop: "{{ users }}"