# Ansible Workshop on IBM i
# Copyright © FormaServe Systems Ltd 2022
# April 2022
#
---
- hosts: ibmi
  vars:
    packages:
      - bob
      - zip
      - tree
  environment:
    PATH: "/QOpenSys/pkgs/bin:/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin"
  collections:
    - ibm.power_ibmi

  tasks:
  - name: Yum Install
    yum:
      name: "{{ packages }}"
      state: present
      use_backend: yum
