# Ansible Workshop on IBM i
# Copyright © FormaServe Systems Ltd 2022
# April 2022
#
---
- hosts: ibmi
  gather_facts: false
  collections:
    - ibm.power_ibmi
  environment:
    PATH: "/QOpenSys/pkgs/bin"

  tasks:
  - name: Verify git has been installed
    stat:
      path: /QOpensys/pkgs/bin/git
    register: git_stat

  - name: Install git if it is not there
    command: /QOpensys/pkgs/bin/yum install git -y
    when: not git_stat.stat.exists

  - name: Update git if installed
    command: /QOpensys/pkgs/bin/yum update git -y
    when: git_stat.stat.exists
