# Ansible Workshop on IBM i
# Copyright © FormaServe Systems Ltd 2022
# April 2022
#
---
- name: Create a user library on all IBMi hosts
  hosts: ibmi
  vars:
    user_profile:
      - JRiddle
      - EmilyY
      - JessicaJ
  gather_facts: true
  collections:
    - ibm.power_ibmi

  tasks:
  - name: Create library for {{ user_profile }}
    ibmi_cl_command:
      cmd: crtlib lib({{ user_profile }})
      joblog: true
    register: crt_lib_result


