# Ansible Workshop on IBM i
# Copyright © FormaServe Systems Ltd 2022
# April 2022
#
---
- name: Check system values on all IBMi hosts
  hosts: ibmi
  gather_facts: true
  collections:
    - ibm.power_ibmi

  tasks:

  - name: Get System Value information
    ibmi_sysval:
      sysvalue:
        - {'name':'qmaxsgnacn', 'expect':'2'}
        - {'name':'qccsid', 'expect':'285'}
      become_user: 'QSECOFR'
      become_user_password: 'NoIdea'

  - name: Compare the returned system values as list
    ibmi_sysval:
      sysvalue:
        - {'name':'QATNPGM', 'expect':'QEZMAIN   QSYS'}
        - {'name':'QATNPGM', 'expect':'QSYS  QEZMAIN'}
        - {'name':'QATNPGM', 'expect':'QEZMAIN  QSYS', 'check':'equal_as_list'}
        - {'name':'QATNPGM', 'expect':'QSYS QEZMAIN', 'check':'equal_as_list'}



