# Ansible Workshop on IBM i
# Copyright © FormaServe Systems Ltd 2022
# April 2022
#
---
- name: Create a user on all IBMi hosts
  hosts: ibmi
  vars:
    user_profile: JRIDDLE
    user_state: present
  gather_facts: true
  collections:
    - ibm.power_ibmi

  tasks:
  - name: Create new users
    ibmi_user_and_group:
      operation: 'create'
      user: "{{ user_profile }}"
      password: 'abc123'
      user_class: '*SECOFR'
      become_user: 'QSECOFR'
      become_user_password: 'NoIdea'
      text: 'Created using Ansible Playbook'
