# Ansible Workshop on IBM i
# Copyright © FormaServe Systems Ltd 2022
# April 2022
#
---
- name: Create a new user on all IBMi hosts
  hosts: ibmi
  gather_facts: true
  collections:
    - ibm.power_ibmi

  tasks:
  - name: Create new user
    ibmi_user_and_group:
      operation: 'create'
      user: 'AEmilyY'
      become_user: 'QSECOFR'
      become_user_password: 'NoIdea'
      text: 'Created using Ansible Playbook'
      user_class: '*SECOFR'

  - name: Create anuvver new user
    ibmi_user_and_group:
      operation: 'create'
      user: 'AJessicaJ'
      become_user: 'QSECOFR'
      become_user_password: 'NoIdea'
      text: 'Created using Ansible Playbook'
      user_class: '*SECOFR'


