# Ansible Workshop on IBM i
# Copyright © FormaServe Systems Ltd 2022
# April 2022
#
---
- name: Create Ansible environment for iUG Workshop
  hosts: ibmi
  gather_facts: false
  collections:
    - ibm.power_ibmi
  vars:
    users:
    - AJESSICAJ
    - AEMILYY

  tasks:
  - name: Create home directory for user
    file:
      path: /home/{{ item }}
      state: directory
      owner: "{{ item }}"
      mode: 0744
    loop: "{{ users }}"

  - name: Create Ansible directory for user
    ibmi_cl_command:
      cmd: crtdir '/home/{{ item }}/ansible'
    loop: "{{ users }}"

  - name: Create .ssh directory for user
    ibmi_cl_command:
      cmd: crtdir '/home/{{ item }}/,ssh'
    loop: "{{ users }}"