# Ansible Workshop on IBM i
# Copyright © FormaServe Systems Ltd 2022
# April 2022
#
---
- name: Loop thro networking interfaces
  gather_facts: false
  hosts: 
    - localhost
  collections:
    - ibm.power_ibmi
  vars:
    parameters:
    - mode: "auto"
      speed: "1000"
      duplex: "full"
    interfaces:
      - Int_One
      - Int_Two

  tasks:
  - name: Debug
    debug:
      msg: >
        mode: {{parameters.0.mode}},
        speed: {{parameters.0.speed}},
        duplex: {{parameters.0.duplex}},
        interface: {{item}}
    loop:
      "{{interfaces}}"