# Copyright © FormaServe Systems Ltd 2022
# April 2022
#
# Create a mew user environment, on all IBM i partitions
# prior to running iUG Workshop on Ansible
#
---
- name: Create Ansible environment for iUG Workshop
  hosts: localhost
  gather_facts: false
  collections:
    - ibm.power_ibmi
  vars:
    users:
    - AJESSICAJ
    - AEMILYY
    - ASAMMYJ
    - ACHLOEY
    - AELLIEJ

  tasks: 
    - name: Looping thro Users
      include_tasks: debug.yml
      loop: "{{ users }}" 