# Ansible Workshop on IBM i
# Copyright © FormaServe Systems Ltd 2022
# April 2022
#

---
- name: Use Secret API Key
  hosts: ibmi

  tasks:
    - name: load variable from secret file
      include_vars:
        file: secret

    - name: Display encrypted variable
      debug:
        msg: "{{ api_key }}"
      no_log: true






