# Ansible Workshop on IBM i
# Copyright © FormaServe Systems Ltd 2022
# April 2022
#

---
- hosts: ibmi
  name: Create new file on the IFS
  vars:
    company: FormaServe
  vars_files:
    - vars/user_profile.yml
  collections:
    - ibm.power_ibmi

  tasks:
  - name: Create new file in test
    copy:
      dest: "vars/git.yml"
      content: |
        line git init
        line git add .
        line git commit -m Initial

  - name: Check all ok!
    stat:
      path: /QOpensys/pkgs/bin/git
    register: git_stat
    include_vars: vars/git.yml





