# Ansible Workshop on IBM i
# Copyright © FormaServe Systems Ltd 2022
# April 2022
#

---
apiVersion: v1
kind: pod
metadata:
  name: pod-yaml2
  labels:
    app: yaml2
spec:
  containers:
  - name: pod-yaml2
    image: busybox
    ports:
    - containerPort: 8080
      protocol: TCP
      volumeMounts:
      - mountPath: /tmp/yaml2
        name: yaml2

